import { useState, useRef, useCallback, type DragEvent } from 'react';
import { analyzeImage, type AnalysisResult } from '../lib/api';

export default function ModelUpload() {
  const [file, setFile] = useState<File | null>(null);
  const [preview, setPreview] = useState<string | null>(null);
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [dragActive, setDragActive] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);

  const handleFile = useCallback((f: File) => {
    if (!f.type.startsWith('image/')) {
      setError('Please select an image file');
      return;
    }
    setFile(f);
    setPreview(URL.createObjectURL(f));
    setResult(null);
    setError('');
  }, []);

  const handleDrag = useCallback((e: DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    if (e.type === 'dragenter' || e.type === 'dragover') {
      setDragActive(true);
    } else if (e.type === 'dragleave') {
      setDragActive(false);
    }
  }, []);

  const handleDrop = useCallback(
    (e: DragEvent) => {
      e.preventDefault();
      e.stopPropagation();
      setDragActive(false);
      if (e.dataTransfer.files?.[0]) {
        handleFile(e.dataTransfer.files[0]);
      }
    },
    [handleFile],
  );

  const handleAnalyze = async () => {
    if (!file) return;
    setLoading(true);
    setError('');
    try {
      const data = await analyzeImage(file);
      setResult({
        ...data,
        certainty: data.certainty * 100,
      });
    } catch (err: any) {
      setError(err.message || 'Analysis failed');
    } finally {
      setLoading(false);
    }
  };

  const handleReset = () => {
    setFile(null);
    setPreview(null);
    setResult(null);
    setError('');
    if (inputRef.current) inputRef.current.value = '';
  };

  const getResultColor = (chance: number) => {
    if (chance >= 70) return '#ef4444';
    if (chance >= 40) return '#f59e0b';
    return '#22c55e';
  };

  const getResultLabel = (chance: number) => {
    if (chance >= 70) return 'Likely AI Generated';
    if (chance >= 40) return 'Uncertain';
    return 'Likely Real';
  };

  return (
    <div className='model-upload'>
      <div className='upload-header'>
        <h1>AI Image Detection</h1>
        <p>Upload an image to analyze whether it was generated by AI</p>
      </div>

      <div className='upload-content'>
        {!preview ? (
          <div
            className={`upload-zone ${dragActive ? 'drag-active' : ''}`}
            onDragEnter={handleDrag}
            onDragLeave={handleDrag}
            onDragOver={handleDrag}
            onDrop={handleDrop}
            onClick={() => inputRef.current?.click()}
          >
            <input
              ref={inputRef}
              type='file'
              accept='image/*'
              onChange={(e) =>
                e.target.files?.[0] && handleFile(e.target.files[0])
              }
              style={{ display: 'none' }}
            />
            <svg
              width='48'
              height='48'
              viewBox='0 0 24 24'
              fill='none'
              stroke='currentColor'
              strokeWidth='1.5'
              strokeLinecap='round'
              strokeLinejoin='round'
              className='upload-icon'
            >
              <path d='M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4' />
              <polyline points='17 8 12 3 7 8' />
              <line x1='12' y1='3' x2='12' y2='15' />
            </svg>
            <p className='upload-text'>Drag & drop an image here</p>
            <p className='upload-subtext'>or click to browse files</p>
            <p className='upload-formats'>Supports: JPG, PNG, WEBP, GIF</p>
          </div>
        ) : (
          <div className='preview-container'>
            <img src={preview} alt='Preview' className='preview-image' />
            <div className='preview-actions'>
              <button onClick={handleReset} className='btn-secondary'>
                <svg
                  width='16'
                  height='16'
                  viewBox='0 0 24 24'
                  fill='none'
                  stroke='currentColor'
                  strokeWidth='2'
                  strokeLinecap='round'
                  strokeLinejoin='round'
                >
                  <line x1='18' y1='6' x2='6' y2='18' />
                  <line x1='6' y1='6' x2='18' y2='18' />
                </svg>
                Remove
              </button>
              <button
                onClick={handleAnalyze}
                className='btn-primary'
                disabled={loading}
              >
                {loading ? (
                  <>
                    <span className='spinner' />
                    Analyzing...
                  </>
                ) : (
                  <>
                    <svg
                      width='16'
                      height='16'
                      viewBox='0 0 24 24'
                      fill='none'
                      stroke='currentColor'
                      strokeWidth='2'
                      strokeLinecap='round'
                      strokeLinejoin='round'
                    >
                      <circle cx='11' cy='11' r='8' />
                      <path d='m21 21-4.3-4.3' />
                    </svg>
                    Analyze Image
                  </>
                )}
              </button>
            </div>
          </div>
        )}

        {error && (
          <div className='upload-error'>
            <svg
              width='16'
              height='16'
              viewBox='0 0 24 24'
              fill='none'
              stroke='currentColor'
              strokeWidth='2'
            >
              <circle cx='12' cy='12' r='10' />
              <line x1='15' y1='9' x2='9' y2='15' />
              <line x1='9' y1='9' x2='15' y2='15' />
            </svg>
            {error}
          </div>
        )}

        {result && (
          <div className='result-card'>
            <div className='result-header'>
              <h2>Analysis Result</h2>
              <span
                className='result-badge'
                style={{ backgroundColor: getResultColor(result.certainty) }}
              >
                {getResultLabel(result.certainty)}
              </span>
            </div>

            <div className='result-gauge'>
              <div className='gauge-circle'>
                <svg viewBox='0 0 120 120' className='gauge-svg'>
                  <circle
                    cx='60'
                    cy='60'
                    r='50'
                    fill='none'
                    stroke='#e5e7eb'
                    strokeWidth='10'
                  />
                  <circle
                    cx='60'
                    cy='60'
                    r='50'
                    fill='none'
                    stroke={getResultColor(result.certainty)}
                    strokeWidth='10'
                    strokeDasharray={`${result.certainty * 3.14} ${314 - result.certainty * 3.14}`}
                    strokeDashoffset='78.5'
                    strokeLinecap='round'
                    className='gauge-fill'
                  />
                </svg>
                <div className='gauge-value'>
                  <span className='gauge-number'>
                    {result.certainty.toFixed(1)}
                  </span>
                  <span className='gauge-percent'>%</span>
                </div>
              </div>
              <p className='gauge-label'>AI Probability</p>
            </div>

            <div className='result-details'>
              <div className='result-detail'>
                <span className='detail-label'>Model</span>
                <span className='detail-value'>{result.modelUsed}</span>
              </div>
              <div className='result-detail'>
                <span className='detail-label'>Processing Time</span>
                <span className='detail-value'>
                  {result.processingTimeMs}ms
                </span>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
